[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Aman Singh", email = "amanscode2005@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.19.2",
    "argon2-cffi>=25.1.0",
    "cryptography>=50.0.1",
    "email-validator>=2.3.0",
    "fastapi>=0.141.1",
    "gitpython>=3.1.62",
    "httpx>=0.28.1",
    "neo4j>=6.3.0",
    "psycopg2-binary>=2.9.12",
    "pydantic-settings>=2.15.0",
    "python-jose[cryptography]>=3.5.0",
    "sentence-transformers>=6.0.1",
    "slowapi>=0.1.10",
    "sqlalchemy>=2.0.52",
    "uvicorn[standard]>=0.52.4",
    "weaviate-client>=4.23.1",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
