"""add github token column

Revision ID: 9b44513e4831
Revises: 9b7856c9744b
Create Date: 2026-09-09 18:43:22.239650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b44513e4831'
down_revision: Union[str, Sequence[str], None] = '9b7856c9744b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encrypted_github_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'encrypted_github_token')
    # ### end Alembic commands ###
